### ISSUE TITLE
Example game site is down

### ISSUE THREAD

**Issue by linonetwo** [3mcd/javelin#101]
http://fps.javelin.games/

It can't be opened...

---

Your lib seems very promising, I'm learning to use it. Thank you for creating and maintaining this.

**Comment by 3mcd** [comment]
Hey, thanks for reporting this. Could you check now? I'm testing a new alpha version of the library which broke the example, so I brought it down rather than leaving up a broken version.

**Comment by 3mcd** [comment]
Also - if you'd like to see the source code for the example, you can get it here: https://github.com/3mcd/javelin-fps

**Comment by linonetwo** [comment]
Ok, I can see it is up, although it is all black screen.

**Comment by 3mcd** [comment]
@linonetwo Try refreshing a few times. I've been having some issues with the VPS I'm using not establishing WebRTC DataChannels reliably.

**Comment by linonetwo** [comment]
It works!

**Comment by 3mcd** [comment]
@linonetwo Awesome. I'll get it working more reliably soon, I just need to set up a STUN/TURN server.

**Comment by 3mcd** [comment]
@linonetwo Connectivity should be much more reliable now! Please keep in mind the example server is running in the US-East region.

**Comment by linonetwo** [comment]
I have a VPN for it, so it is pretty smooth.

I can see you add detailed doc for it, it is very helpful!
