### ISSUE TITLE
Interoperate with UI library, for example, React

### ISSUE THREAD

**Issue by linonetwo** [3mcd/javelin#104]
I'm trying to create a thing that works like react-redux to allow react components render things into the canvas (using react-pixi-fiber) based on data inside the ECS world.

The pseudo-code is

```js
import { useContext, cloneElement } from "react"
import { createComponentFilter, query, World } from "@javelin/ecs"

const connect = (component, selector: ReturnType<query>, topic) => (WrappedReactComponent) => {

  const world = useContext(ContextContainsWorld)

  // there will be lots of components of same type to be render, using same React component
  // so we return an array 
  const reactComponentsToRender = []
  for (const [entity, [...data]] of selector(world)) {
    reactComponentsToRender.push(<WrappedComponent data={data} topic={topic} />)
  }
  return (reactOwnProps) => {
    return reactComponentsToRender.map(element => cloneElement(element, reactOwnProps))
  }
}

```

In this way, we can create a `<Pawn />` component, and render 10 Pawn if there are 10 PawnComponent in the ECS world.

Use it like:

```js
import Position from "../ecs/components/position"
import RightClickTopic from "../ecs/topics/rightClick"

function Pawn(props) {
  return // some react-pixi-fiber components
  // ... onClick={() => props.topic.push(message)}  ... 
}

const visible = createComponentFilter<typeof Position>(() => component =>
  component.x >= 0 && component.x <= 800 && component.y >= 0,
)
const culledPositions = query(visible(Position))

export default connect(Position, culledPositions, RightClickTopic)(Pawn)
```

Do you use react and redux? What do you think?

One possible problem is that I'm not calling query inside a system...
Another problem is that I need to make data immutable, so react will rerender iff data is changed.

**Comment by linonetwo** [comment]
Leave this as a side project, I'm going to call pixi directly to finish my game first...

Although I will keep using React to draw UI (So I can use beautiful opensource UI libs), and take a look of this later.

**Comment by 3mcd** [comment]
Interesting idea! I do use React/Redux frequently -- and haven't put too much thought into how the two libraries might interoperate yet, but I'm happy to use this issue as a place to discuss it.

The `@javelin/devtools` package shows an example of how you might display information from the ECS in a React application, but it does so by iterating through the world's internal storage manually, every 500ms or so.

Here's some pseudocode of a hook called `useMapQuery` that would map the results of a query to an array of React components, each with a corresponding entity/component collection. Under the hood, `useMapQuery` would really just register a new system with the World (once, of course), and re-render the calling React component when `world.tick` is called.

```typescript
import { Position, visible } from "game";
import { mapQueryToComponent } from "ui/helpers";
import { useWorld, useMapQuery } from "ui/hooks";

const culledPositions = query(visible(Position);

function MyComponent() {
    const world = useWorld();
    const pawns = useMapQuery(culledPositions, Pawn, world);

    return pawns;
}

function Pawn(props: MappedQueryProps<typeof culledPositions>) {
    const { entity, components } = props;
    const position = getMappedComponent(components, Position);
    // ...
}
```

I'll put some more thoughts down when I have time.

**Comment by linonetwo** [comment]
I can see you are using React as "instant mode" Graphical API in the dev-tool, which can't utilize React's shadow dom feature...

---

I have some question about how to implement that hook:

To register a new system, we need to use useEffect, which requires us to return an unregister function, but seems we cannot easily unregister things?

And in the doc you said it is bad to store queried components into an array, but seems we need to do so like

```js
  const reactComponentsToRender = []
  for (const [entity, [...data]] of selector(world)) {
    reactComponentsToRender.push(<Pawn data={data} topic={topic} />)
    // or store data into array first, and map to components later
  }
```

**Comment by 3mcd** [comment]
> To register a new system in the hook, we need to use useEffect, which requires us to return an unregister function, but seems we cannot easily unregister things?

Yep, good point. I'll get this added ASAP.

> And in the doc you said it is bad to store queried components into an array, but seems we need to do so like...

This section of the docs needs a few changes. It's totally okay to create a new array with `...` or `.slice()`.

Here's a gist with an example of how the related hook(s) and their dependencies might be implemented.
https://gist.github.com/3mcd/87d8bc51782cbf3c4e41225ab38c5243

The provider registers a single system which executes a list of callbacks (called subsystems in the example) that are registered by the `useMappedQuery` hook. This is just scratch work so don't expect it to run on the first try!! Note the use of the hypothetical method `removeSystem`:

**Comment by linonetwo** [comment]
I can successfully render Pawn using the hook you proposed!

But I encounter a problem that I can't spawn from React button click

I'm click button and push topic here https://github.com/linonetwo/Eternity-Foundation/blob/9b610453b959f513c2e926b41504217b9dd8ea5d/src/pages/components/HUD/index.tsx#L35-L37

I can get topic here https://github.com/linonetwo/Eternity-Foundation/blob/master/src/ecs/systems/spawn.ts

But seems no new entity is added to the world... Do you know the possible cause?

**Comment by 3mcd** [comment]
Good, glad you figured it out!!

**Comment by linonetwo** [comment]
Now I can ask a system to load map using topic:

```src/ecs/topics/map.ts```

```js
/* eslint-disable @typescript-eslint/no-use-before-define */
import { createTopic } from '@javelin/ecs';

export enum MapCommandType {
  load,
}
type MapCommands = ILoadMapCommand;

// ("spawnPawn", entity: number, position: [x: number, y: number])
type ILoadMapCommand = [MapCommandType.load, [{ modName: string; mapName: string }]];
export const loadMap = (mapInfo: { modName: string; mapName: string }): void =>
  mapTopic.push([MapCommandType.load, [mapInfo]] as ILoadMapCommand);

export const mapTopic = createTopic<MapCommands>();
```

I export an `loadMap` function here, and in React side

```js
<Button onClick={() => loadMap(mapInfo)}>{mapInfo.mapName.replace('.json', '')}</Button>
```

So I think I can close this issue now, Interoperate with React is working now, mostly done by using your solution https://gist.github.com/3mcd/87d8bc51782cbf3c4e41225ab38c5243
