### ISSUE TITLE
Question: cache simulation or world state

### ISSUE THREAD

**Issue by DrSensor** [3mcd/javelin#117]
Is there a lifecycle hook or a mechanism that I can tap into to listen every change in the world?

My case is to cache all entities into localStorage at specific _interval_ so it can resume the simulation when browser accidently closed the tab or crashed.

(maybe something like `queryAll()` entities 🤔, don't know if it's good idea)

**Comment by 3mcd** [comment]
Another really good idea. I'll work on getting this in this week.

```
const worldStorageKey = "world_storage";

function persistSystem(tick: number) {
  if (tick === 0) {
    world.restore(localStorage.getItem(worldStorageKey));
  } else if (tick % 100 === 0) {
    localStorage.setItem(worldStorageKey, JSON.stringify(world.getSnapshot()));
  }
}
```

**Comment by DrSensor** [comment]
That's neat! It also open the possibility for snapshot tests
