### ISSUE TITLE
Dealing with non-serializable state

### ISSUE THREAD

**Issue by a-type** [3mcd/javelin#121]
Hi there! I've been building my own TypeScript ECS, but I found Javelin and I agree with basically all the implementation decisions, so I'd like to use it!

Javelin does seem to have one opinion I'm having a bit of trouble adjusting to - it appears that all components must be serializable (just based on schema constraints).

I like that a lot in principle. Has a lot of great implications for networking or webworker integration.

I'm curious though, how live state like a physics RigidBody would be best stored, accessed, and disposed.

In other ECS, like [ecsy](https://ecsy.io/) for instance, there's a concept of a "State Component" which lives only at runtime. In my own implementation I had that concept, so to add a RigidBody you might attach a serializable `BodyConfig` component, and then the System would query `BodyConfig, Not(Body)` entities and add a `Body` to those on frame 1 which stores a reference to the actual RigidBody from the physics simulation library.

When the entity is destroyed, or the body should otherwise be removed, the world would remove the `BodyConfig` component so that it's left with just `Body` - and the system would have another query for `Body, Not(BodyConfig)` which disposes the rigidbody and removes the `Body`.

There are some downsides to that approach (including forgetting to do the cleanup step), and it's a bit obtuse to learn. But it does have nice properties of easily and efficiently associating non-serializable state to an entity utilizing the ECS framework.

How would you recommend dealing with object references like that? I noticed in one of the code examples in the docs you have a `getBodyByEntity` function - is that the idea, just to store things in global state and lookup using entity IDs?

**Comment by a-type** [comment]
Slighly related, the ability to nest the schema a bit might also be nice without compromising serializability - though I can see how exposing only primitives might help push users toward simpler, more focused components.

**Comment by 3mcd** [comment]
Another great question @a-type. This is very similar to what I was experimenting with in the [Javelin FPS](https://github.com/3mcd/javelin-fps) example. Check out the [`maintain.ts` "subsystem"](https://github.com/3mcd/javelin-fps/blob/master/common/systems/physics/subsystems/maintain.ts) (just a little pattern I've been playing around with) that does the cleanup/teardown part, independent from the actual physics logic of the game.

I agree it would be nice to have an idiomatic way to do this, ideally where the "State Component" object could be stored alongside the related component in the component storage to make lookups fast. There's also nothing really preventing storage of un-serializable components today as long a the instances have a `type` field. So we could probably work this in fairly easily.

**Comment by panuchka** [comment]
If we keep a sort of duplicate reference to mesh/rigidbody of the 3d library x, doesn't that raise some performance questions since these objects are not actually pooled in any way and can be created on the fly? I'm afraid of the garbage collection...

**Comment by a-type** [comment]
I think I was actually mistaken about the nested structures - it seems possible just by nesting the schema currently. Not sure about serialization, as I am only working on a singleplayer and singlethreaded game at the moment.

**Comment by 3mcd** [comment]
Sorry for the slow turnaround on these issues. Things have been crazy at home (as I know they have been for everyone).

> If we keep a sort of duplicate reference to mesh/rigidbody of the 3d library x, doesn't that raise some performance questions since these objects are not actually pooled in any way and can be created on the fly? I'm afraid of the garbage collection...

To @a-type's point, this is probably a concern of the third-party library. Those objects can still be pooled by the library (or using your own pool). But it's of course your responsibility to dispose of those objects in the way the library expects.

As for the original ask, I'm just going to jump right into a code example. What about something like this:

```ts
const queries = {
  attached: attached(added(Body)),
  detached: query(detached(Body)),
  bodies: query(Body),
}
const physics = (world: World, dt: number, state: SystemState<LibraryBody>) => {
  for (const [entity, body] of queries.attached(world)) {
    state.set(entity, new Library.Body(mapBodyToLibraryAttrs(body))
  }

  for (const [entity, body] of queries.detached(world)) {
    const libraryBody = state.get(entity)
    libraryBody.destroy()
    state.delete(entity)
  }
  
  for (const [entity, body] of queries.bodies(world)) {
    const libraryBody = state.get(entity)
    ...
  }
}
```

A third parameter could be added to systems called `state` which maintains a map of entity=>SSC. This API would limit one SSC per entity per system.

**Comment by a-type** [comment]
Full disclosure, I did go back to tinkering with my own ECS in the past month or so - not because of your absence, but there were a few ideas I wanted to explore which don't fit well into Javelin's multiplayer focus. I wanted to explore this space specifically without worrying about networking synchronization, since I don't plan on making networked games.

I've been [thinking hard about this problem](https://github.com/a-type/0g/issues/24) in the context of my library and done several prototypes of various implementations. I hadn't considered doing a state storage per System, though, that's a neat idea.

I think the caveat though is that it seems to confine state to the System, which would be a big limitation for something like a physics body. I can see use cases where different Systems would want access to the rigidbody state associated with an Entity. I believe currently Javelin appears to encourage using Topics to pass messages to the 'owner' System, which might help address that use case - interested Systems would just queue topic messages.

I'm not totally sure of the design considerations required for networking, so that might be the best solution for Javelin. My current prototype for my library has `State` which is just a special type of `Component` that isn't serialized, as I mentioned in the original post. Systems interested in interacting with a rigidbody for an entity would just query for the appropriate State Component and act on it directly, which feels a little non-ECS-y, but is pretty intuitive.

The other outcome of my current prototype is that I'm actually encouraging a pattern of creating a large number of systems to manage common sets of components. I like the freedom of creating many small, focused systems. Constraining state to be internal to a single System would also discourage that, but Javelin may have different patterns and goals!

**Comment by 3mcd** [comment]
I drew inspiration from 0g's effects and implemented [something similar in Javelin](https://javelin.games/ecs/effects/). Effects partially solve this problem as you alluded to within your awesome GitHub issue. But I still feel that any non-serializable or third-party state should exist outside of the `World` within effects. That being said, it should be easy to reconcile proprietary state with third party objects via "foreign keys", `WeakMap`s, etc. So I'm going to close this for now.
