### ISSUE TITLE
"not" filters

### ISSUE THREAD

**Issue by a-type** [3mcd/javelin#125]
It would be useful to have a query filter that tests for the absence of a component. For example, I'm experimenting with maintaining an entity hierarchy datastructure and using components to declare the hierarchy and a system to enforce it. For this system, I'd like any entity without a `Child` component to be considered a 'root' entity and added to the root node directly. To do so I'll need to filter by entities without the `Child` component (not just detached, as they never had it) to add them to the tree.

I don't think this can be implemented as a custom filter as it appears that custom filters require the presence of their topic Component type, which is obviously incompatible with a `not` filter.

**Comment by 3mcd** [comment]
This is a great idea, and something that should definitely be added as part of a 1.0 release. You're right that it wouldn't be possible to implement as a custom filter, and you probably wouldn't want to, since we could optimize it a bit by having access to the library internals. I'll start thinking about this (and all your other requests) as I plan on starting to spend more of my free time on this project again over the next couple of weeks.

**Comment by a-type** [comment]
Thanks for considering it, and I'm glad to see the project still has your attention.

**Comment by 3mcd** [comment]
I think this should be fairly easy to implement, but the concept of a filter that eliminates entities based on the absence of a component raises an interesting question. A query's selector directly maps to the iterable's results at both compile time and run time. If we keep it this way, should we simply replace the value with `null` at the index corresponding to the type filtered with `not`?

```ts
const root = query(not(Child), Node)
const system = (world) => {
  for (const [entity, [, node]] of world) {
   
   }
}
```

**Comment by a-type** [comment]
Ah, that's an interesting constraint. I imagine there is a way of using TypeScript to eliminate gaps, but it would also probably take a lot of trial and error to find it... null entries (typed as `never` even) could be a decent way to do it.
