### ISSUE TITLE
0.19.4

### ISSUE THREAD

**Issue by 3mcd** [3mcd/javelin#133]
0.19.4

**Comment by linonetwo** [comment]
Glad to see you get back to this!

**Comment by djradon** [comment]
I'm glad to see the progress too! Have you considered [setting up sponsorship](https://docs.github.com/en/github/supporting-the-open-source-community-with-github-sponsors/setting-up-github-sponsors-for-your-user-account)?

**Comment by 3mcd** [comment]
I hadn't really considered it yet. But the Javelin seems to have gained a little traction recently so it might not be a bad idea. Thanks for the recommendation, I'll set it up today :)
