### ISSUE TITLE
MessageHandler throws error when browser resumes processing reliable messages

### ISSUE THREAD

**Issue by 3mcd** [3mcd/javelin#136]
The server tick counter is not included in reliable messages, so there is no guarantee (or way) to ensure that detach/destroy world ops are spaced out between ticks. This can cause errors if the packets aren't evenly spaced, or if the browser temporarily halts processing messages (like while debugging or switching to a new tab).

**Comment by kenjinp** [comment]
IS this related to the messages where it cannot find a local counterpart?
![Screenshot 2021-04-11 at 01 20 51](https://user-images.githubusercontent.com/5485824/114287053-387c2800-9a64-11eb-9715-e0226b123aa1.png)

**Comment by kenjinp** [comment]
Looks like my issue above is related to something else:

I've dug into the code and it appears that the message producer doesn't allow for spawning entities after the initial message. Seems like an oversight? I can create a PR for that, or a new issue.

I fixed it like this:
<img width="478" alt="Screenshot 2021-04-11 at 16 07 08" src="https://user-images.githubusercontent.com/5485824/114307501-335cbe80-9ae0-11eb-8a7b-f9065b3fc91b.png">

**Comment by 3mcd** [comment]
Good catch! Yes this is a pretty big oversight and could have been caught with tests. I currently have some tests written for MessageHandler, but not MessageProducer. Thanks for catching this, and feel free to create a PR (no need for a separate issue)!

I'm working on a new version of the networking protocol that I hope will bring several improvements (less opiniated, faster, smaller messages, lower memory usage). The `net` package in it's current state is a true MVP and is missing features that a library like Javelin should have. I hope to have the new protocol released within the next week.

**Comment by kenjinp** [comment]
Thanks :) I'm very happy so far, happy to contribute elsewhere. I'll create a PR soon.

**Comment by 3mcd** [comment]
This issue has been fixed in the 1.0 alpha release(s).
