### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by linonetwo** [3mcd/javelin#148]
I can see there is a benchmark for js ecs frameworks, maybe you can add yours into it https://github.com/noctjs/ecs-benchmark
So more people will know your lib

**Comment by 3mcd** [comment]
Awesome recommendation! I'm aware of this benchmark and actually implemented the perf cases this weekend, just need to push up a PR. I did notice some lackluster performance while working on this, and have a separate branch that aims to give a lower level API for performance-intensive applications while providing the current API for folks who can afford to sacrifice performance for readability. The good news is with the lower level query API, Javelin sits right under BitECS in all categories.

The new API will include two new ways of iterating queries. The first, `forEach` is ~4x faster than `for..of` loops:

```ts
const moving = query(Position, Velocity)

moving.forEach((entity, [p, v]) => {
  p.x += v.x
  ...
})
```

The second, iterating a query's records manually, is around ~4x faster than `forEach`, and places Javelin under BitECS (which is still significantly faster) in each of the benchmark's perf cases:

```ts
for (const [entities, [a, b]] of moving.records) {
  for (let i = 0; i < entities.length; i++) {
    p[i].x += v[i].x
  }
}
```

The benchmark results look like

```
javelin-ecs
  packed_1        61,114 op/s
  packed_5        78,344 op/s
  simple_iter     43,113 op/s
  frag_iter       131,418 op/s
  entity_cycle    319 op/s
  add_remove      3,332 op/s
```

**Comment by linonetwo** [comment]
I think I will choose the fastest approach, if they can do the same thing, this little difference in writing doesn't matter I think.

**Comment by 3mcd** [comment]
This was implemented in https://github.com/noctjs/ecs-benchmark/pull/33. Thanks again for the suggestion @linonetwo!
