### ISSUE TITLE
Question: when exactly should one use world.getObserved vs world.tryGet?

### ISSUE THREAD

**Issue by kenjinp** [3mcd/javelin#161]
Perhaps I just don't understand the docs. Why would I try to use one versus the other, especially because they seem to return the same thing

**Comment by 3mcd** [comment]
Good question. Apologies for the vagueness around change detection in the documentation.

Practically, the difference is that you must use `getObserved` to send changes reliably. That is to say, if you flag a component type for reliable synchronization (i.e. no `priority`), only the mutations made to "observed" instances of that component type will be transmitted.

Specifically, `getObserved` returns a `Proxy`-fied copy of a component that tracks and stores mutations (e.g. assignments and mutating array method calls) made to the component through via the proxy. `MessageProducer` reads these changes and serializes/sends only the path-value pairs (e.g. `["a.b.prop", 123]`) that were changed.

**Comment by kenjinp** [comment]
Fantastic explanation,  now it's very clear :)

**Comment by 3mcd** [comment]
Glad it helped! I'll update the docs with something similar 😄
