### ISSUE TITLE
world.tryGet throws an error if an entity has been removed from the system already

### ISSUE THREAD

**Issue by kenjinp** [3mcd/javelin#162]
Perhaps this is because I'm using world.tryGet outside of a system context, because using this inside a query in the system should guarantee that the entity exists. However, outside of that there's cases where a system has deleted an entity (like from a server despawn event). 

I think that the name entails it will return a component or null/undefined and not throw.?

**Comment by 3mcd** [comment]
Could you share the error message? You have a good point, I think if the entity was destroyed then `tryGet` should probably not throw.

**Comment by kenjinp** [comment]
Here's the error:
![Screenshot 2021-04-15 at 09 25 22](https://user-images.githubusercontent.com/5485824/114830504-9003f600-9dcc-11eb-8b9c-4ebf85e4bd22.png)

I have to wrap code like this, which feels duplicitous :)
![Screenshot 2021-04-15 at 09 26 03](https://user-images.githubusercontent.com/5485824/114830687-c5104880-9dcc-11eb-874c-435b2485e664.png)
