### ISSUE TITLE
Cannot find name 'A' / '$Args'.

### ISSUE THREAD

**Issue by Marty** [3mcd/javelin#172]
Hi,

I just started using Javelin and get this error when transpiling my ts code.
```
{
	"resource": "/home/xx/Documents/sandbox/xx/xx/node_modules/@javelin/ecs/dist/cjs/effects/web/json.d.ts",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "Cannot find name 'A'.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 99,
	"endLineNumber": 2,
	"endColumn": 99
}
```
same on `request.d.ts`.

I downgraded to javelin `0.22.0`.
Before I used `1.0.0-alpha4` where I got basically the same error only that it was `$Args` instead of `A`.
Am I doing something wrong? I am new to Typescript and still learning as I go.

My `tsconfig.json`
```
{
    "compilerOptions": {
        "experimentalDecorators": true,
        "target": "es2016",
        "module": "commonjs",
        "outDir": "./dist",
        "inlineSourceMap": true,
        "esModuleInterop": true,
        "strict": true
    }
}
```

**Comment by 3mcd** [comment]
This appears to be related to https://github.com/microsoft/TypeScript/issues/42079. It's a bit over my head, but a fix is scheduled to be scheduled with TypeScript 4.4.1, so we'll check back in then.

**Comment by Marty** [comment]
In the meantime, the workaround with `"skipLibCheck": true` in my `tsconfig.json` works.
