### ISSUE TITLE
Docs website is out of sync with javelin/docs

### ISSUE THREAD

**Issue by montoyaaguirre** [3mcd/javelin#176]
https://javelin.games/ecs/world/ is referring to a `world.tick` function which is now called step. 

The files on javelin/docs seem correct but probably have not been deployed.

**Comment by 3mcd** [comment]
Thanks for the report, and so sorry the new docs took so long to be pushed. This should be fixed now.

**Comment by montoyaaguirre** [comment]
Thanks! The website docs are up to date now.
