### ISSUE TITLE
Register system after World is instantiated

### ISSUE THREAD

**Issue by 3mcd** [3mcd/javelin#47]
Currently systems are registered via the `createWorld` factory:

```ts
const world = createWorld([systemA, systemB]);
```

It would be useful to be able to add a system after the world is instantiated:

```ts
world.addSystem(systemC);
```

**Comment by rjmontgo** [comment]
Happy to take this one!

The immediate naive solution that comes to mind is the following:

```
export const createWorld = <T>(systems: System<T>[]): World<T> => {
// ....
    function addSystem(system: System<T>) {
       systems.push(system);
    }
// ....
)
```
My main concern is that I don't know if that parameter information will be preserved - my instinct is yes because javascript does pass by reference for arrays.

**Comment by rjmontgo** [comment]
I wanted to confirm my suspicion that this would work so here is a snippet to prove that the references are preserved.

```
const test = (arr) => {
  
  function addThing(thing) {
    arr.push(thing);
  }

  function getThings() {
    return arr;
  }

  return {
    addThing,
    getThings
  }

}

var obj = test([1])
console.log(obj.getThings());
obj.addThing(2);
console.log(obj.getThings());
obj.addThing(3);
console.log(obj.getThings());
```

**Comment by 3mcd** [comment]
Yeah looks like a sound implementation :)

**Comment by rjmontgo** [comment]
It looks like my `Fixes` tag didn't auto close this issue. I'll just close it manually.

**Comment by 3mcd** [comment]
@rjmontgo Looks like the tests are failing w/ this change. Probably just related to the manual mocks. I still need to get automated tests working on PRs, so my bad.
