### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by 3mcd** [3mcd/javelin#49]
I'd like to have an idiomatic way of handling events with Javelin ECS. Pulling off events in a "pure" fashion in ECS is hard.

I propose we pass events as another argument to systems so they can remain as self-contained as possible, without relying on a global/singleton event bus.

Systems can target other systems using a new method, `world.dispatch`.

Example API:

**input.ts**
```ts
import { physics } from "./physics";

function input(dt: number, world: World) {
  const playerEntity = getPlayerEntity(world);

  if (keyboard.space) {
    world.dispatch(physics, { type: "apply_force", entity: playerEntity, force: [0, 0, 10] });
  }
}
```

**physics.ts**

```ts
type PhysicsEvent = { type: "apply_force", entity: number, force: Vector3 }

const engine = new PhysicsEngine();
const bodies = new Map<number, PhysicsEngineBody>();

function physics(dt: number, world: World, events: PhysicsEvent[]) {
  events.forEach(e => {
    if (e.type === "apply_force") {
      const body = bodies.get(e.entity);
      engine.applyForce(body, e.force);
    }
  });
  // ...
}
```

**Comment by 3mcd** [comment]
We could also take a more pub-sub approach where events are broadcast to topics (e.g. strings). Systems can "subscribe" to those topics, e.g.

```ts
world.dispatch("physics", { type: "apply_force", ...);
```

```ts
for (const e of world.events("physics") {
  // ...
}
```

**Comment by rjmontgo** [comment]
I personally think the second approach is better. 

One possible change that might be good from a user perspective is if instead of having physics query the world for the topic it's subscribed to we attach a callback to the `world` object that executes based on events that are listed under a topic. I *think* this would be a bit more performant as it means you aren't making unnecessary queries to the world with each system that you have. 

**world.ts**
```ts

interface topic {
   events: Event[],
   subscribers: {
      notify: (event: Event) => void
   }
}

const createWorld = () => {
   function tick() {
       // ...

       /* 
          I believe that we would want this to go 
          *before* executing each system since we 
           want these to execute on the next tick 
        */
      world.topics.forEach(topic => {
         topic.events.forEach(event => {
            topic.subscribers.forEach(subscriber => {
               subscriber.notify(event);
            }
         }
      })

       // Execute all systems     
   }

   function subscribe(topic) {
     // ...
  }
}
```

This I think would centralize a lot of the code and be what I would sort of expect from what I'm viewing as essentially a reducer with states and actions swapped for systems and events. But I could be totally wrong on that.

**Comment by rjmontgo** [comment]
on second thought - please disregard my above comment

**Comment by rjmontgo** [comment]
So my strategy has basically moved down one level, instead of registering the callback at the world level the user could manage it at the system level which I believe is what you are indicating. In that case think solution 2 is the way to go.

**Comment by 3mcd** [comment]
New proposal based on Slack conversations:

**topics/physics.ts**
```ts
type PhysicsEvent = 
  | { type: "apply_force", entity: number, force: Vector3 }
  | { type: "rotate_body", entity: number, quaternion: Quaternion }
  | { type: "apply_impulse", entity: number, force: Vector3 };

export const physicsTopic = createTopic<PhysicsEvent>("physics");
```

**systems/input.ts**
```ts
export function inputSystem() {
  if (spacebarPressed) {
    world.dispatch(physicsTopic, { type: "apply_force", ... });
  }
}
```
